// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqIohAFWn6SoL3sWVKhRI52EAtjbEIqEM',
    appId: '1:882795617956:web:e870b6638433c3257b9031',
    messagingSenderId: '882795617956',
    projectId: 'gradgigs-eb479',
    authDomain: 'gradgigs-eb479.firebaseapp.com',
    storageBucket: 'gradgigs-eb479.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGw8H6GbbAzxYjIJSVWGOw8kAIW91DGgs',
    appId: '1:882795617956:android:13884243f19cec897b9031',
    messagingSenderId: '882795617956',
    projectId: 'gradgigs-eb479',
    storageBucket: 'gradgigs-eb479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhGaB-e7tcQYjxCOjvnFUR6DDx1T9x6M',
    appId: '1:882795617956:ios:653c90207a748fc67b9031',
    messagingSenderId: '882795617956',
    projectId: 'gradgigs-eb479',
    storageBucket: 'gradgigs-eb479.appspot.com',
    iosBundleId: 'com.example.gradgigs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVhGaB-e7tcQYjxCOjvnFUR6DDx1T9x6M',
    appId: '1:882795617956:ios:653c90207a748fc67b9031',
    messagingSenderId: '882795617956',
    projectId: 'gradgigs-eb479',
    storageBucket: 'gradgigs-eb479.appspot.com',
    iosBundleId: 'com.example.gradgigs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqIohAFWn6SoL3sWVKhRI52EAtjbEIqEM',
    appId: '1:882795617956:web:32677c48f21fa2b87b9031',
    messagingSenderId: '882795617956',
    projectId: 'gradgigs-eb479',
    authDomain: 'gradgigs-eb479.firebaseapp.com',
    storageBucket: 'gradgigs-eb479.appspot.com',
  );
}
